"""initial schema

Revision ID: 14e7271fac68
Revises: 
Create Date: 2026-06-21 18:34:16.050123
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '14e7271fac68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiobooks',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=160), nullable=True),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audiobooks'))
    )
    op.create_index(op.f('ix_audiobooks_is_free'), 'audiobooks', ['is_free'], unique=False)
    op.create_index(op.f('ix_audiobooks_is_published'), 'audiobooks', ['is_published'], unique=False)
    op.create_index(op.f('ix_audiobooks_slug'), 'audiobooks', ['slug'], unique=True)
    op.create_table('courses',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('level', sa.String(length=40), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    op.create_index(op.f('ix_courses_is_published'), 'courses', ['is_published'], unique=False)
    op.create_index(op.f('ix_courses_slug'), 'courses', ['slug'], unique=True)
    op.create_table('observation_tests',
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'video', name='media_type'), nullable=False),
    sa.Column('media_url', sa.String(length=512), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_option', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('psychology', 'body_language', 'observation', name='observation_category'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observation_tests'))
    )
    op.create_index(op.f('ix_observation_tests_is_active'), 'observation_tests', ['is_active'], unique=False)
    op.create_index(op.f('ix_observation_tests_order_index'), 'observation_tests', ['order_index'], unique=False)
    op.create_table('pronunciation_references',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('reference_audio_url', sa.String(length=512), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pronunciation_references'))
    )
    op.create_table('users',
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('user', 'curator', 'admin', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audiobook_pages',
    sa.Column('audiobook_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], name=op.f('fk_audiobook_pages_audiobook_id_audiobooks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audiobook_pages')),
    sa.UniqueConstraint('audiobook_id', 'page_number', name='audiobook_page')
    )
    op.create_index(op.f('ix_audiobook_pages_audiobook_id'), 'audiobook_pages', ['audiobook_id'], unique=False)
    op.create_table('audiobook_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('audiobook_id', sa.Uuid(), nullable=False),
    sa.Column('current_page', sa.Integer(), nullable=False),
    sa.Column('last_listened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], name=op.f('fk_audiobook_progress_audiobook_id_audiobooks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audiobook_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audiobook_progress')),
    sa.UniqueConstraint('user_id', 'audiobook_id', name='user_audiobook')
    )
    op.create_index(op.f('ix_audiobook_progress_audiobook_id'), 'audiobook_progress', ['audiobook_id'], unique=False)
    op.create_index(op.f('ix_audiobook_progress_user_id'), 'audiobook_progress', ['user_id'], unique=False)
    op.create_table('auth_identities',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('phone', 'google', 'telegram', 'password', name='auth_provider'), nullable=False),
    sa.Column('provider_uid', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_identities')),
    sa.UniqueConstraint('provider', 'provider_uid', name='provider_uid')
    )
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.create_table('certificates',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('serial_number', sa.String(length=40), nullable=False),
    sa.Column('pdf_url', sa.String(length=512), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_certificates_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_certificates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates'))
    )
    op.create_index(op.f('ix_certificates_course_id'), 'certificates', ['course_id'], unique=False)
    op.create_index(op.f('ix_certificates_serial_number'), 'certificates', ['serial_number'], unique=True)
    op.create_index(op.f('ix_certificates_user_id'), 'certificates', ['user_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'cancelled', name='enrollment_status'), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_enrollments_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_enrollments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('user_id', 'course_id', name='user_course')
    )
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollments_user_id'), 'enrollments', ['user_id'], unique=False)
    op.create_table('lessons',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=512), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('is_voice_exercise', sa.Boolean(), nullable=False),
    sa.Column('voice_exercise_prompt', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_lessons_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons'))
    )
    op.create_index(op.f('ix_lessons_course_id'), 'lessons', ['course_id'], unique=False)
    op.create_table('observation_attempts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_observation_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observation_attempts'))
    )
    op.create_index(op.f('ix_observation_attempts_user_id'), 'observation_attempts', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider', sa.Enum('uzum', 'uzum_nasiya', 'atmos', name='payment_provider'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'refunded', name='payment_status'), nullable=False),
    sa.Column('purpose', sa.Enum('course', 'audiobook', 'subscription', name='payment_purpose'), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_external_id'), 'payments', ['external_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('push_notifications',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('audience', sa.Enum('all', 'course', 'user', name='push_audience'), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('sent_by', sa.Uuid(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], name=op.f('fk_push_notifications_sent_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_notifications'))
    )
    op.create_table('push_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.Enum('ios', 'android', 'web', name='platform'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_push_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_tokens')),
    sa.UniqueConstraint('token', name=op.f('uq_push_tokens_token'))
    )
    op.create_index(op.f('ix_push_tokens_user_id'), 'push_tokens', ['user_id'], unique=False)
    op.create_table('speech_analyses',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('audio_url', sa.String(length=512), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='analysis_status'), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('meaning_score', sa.Integer(), nullable=True),
    sa.Column('fluency_score', sa.Integer(), nullable=True),
    sa.Column('filler_words', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pauses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('info_balance', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_speech_analyses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speech_analyses'))
    )
    op.create_index(op.f('ix_speech_analyses_status'), 'speech_analyses', ['status'], unique=False)
    op.create_index(op.f('ix_speech_analyses_user_id'), 'speech_analyses', ['user_id'], unique=False)
    op.create_table('voice_analyses',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('reference_text', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=512), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='analysis_status'), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('accuracy_score', sa.Integer(), nullable=True),
    sa.Column('word_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phoneme_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['pronunciation_references.id'], name=op.f('fk_voice_analyses_reference_id_pronunciation_references'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_voice_analyses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voice_analyses'))
    )
    op.create_index(op.f('ix_voice_analyses_status'), 'voice_analyses', ['status'], unique=False)
    op.create_index(op.f('ix_voice_analyses_user_id'), 'voice_analyses', ['user_id'], unique=False)
    op.create_table('homeworks',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('submission_text', sa.Text(), nullable=True),
    sa.Column('submission_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'reviewed', 'returned', name='homework_status'), nullable=False),
    sa.Column('curator_id', sa.Uuid(), nullable=True),
    sa.Column('curator_score', sa.Integer(), nullable=True),
    sa.Column('curator_feedback', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['curator_id'], ['users.id'], name=op.f('fk_homeworks_curator_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_homeworks_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_homeworks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_homeworks'))
    )
    op.create_index(op.f('ix_homeworks_lesson_id'), 'homeworks', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_homeworks_status'), 'homeworks', ['status'], unique=False)
    op.create_index(op.f('ix_homeworks_user_id'), 'homeworks', ['user_id'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('auto_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_lesson_progress_enrollment_id_enrollments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_progress_lesson_id_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_progress')),
    sa.UniqueConstraint('enrollment_id', 'lesson_id', name='enrollment_lesson')
    )
    op.create_index(op.f('ix_lesson_progress_enrollment_id'), 'lesson_progress', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_lesson_id'), 'lesson_progress', ['lesson_id'], unique=False)
    op.create_table('lesson_questions',
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_questions_lesson_id_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_questions'))
    )
    op.create_index(op.f('ix_lesson_questions_lesson_id'), 'lesson_questions', ['lesson_id'], unique=False)
    op.create_table('observation_answers',
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('selected_option', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['observation_attempts.id'], name=op.f('fk_observation_answers_attempt_id_observation_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['observation_tests.id'], name=op.f('fk_observation_answers_test_id_observation_tests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observation_answers'))
    )
    op.create_index(op.f('ix_observation_answers_attempt_id'), 'observation_answers', ['attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observation_answers_attempt_id'), table_name='observation_answers')
    op.drop_table('observation_answers')
    op.drop_index(op.f('ix_lesson_questions_lesson_id'), table_name='lesson_questions')
    op.drop_table('lesson_questions')
    op.drop_index(op.f('ix_lesson_progress_lesson_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_enrollment_id'), table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index(op.f('ix_homeworks_user_id'), table_name='homeworks')
    op.drop_index(op.f('ix_homeworks_status'), table_name='homeworks')
    op.drop_index(op.f('ix_homeworks_lesson_id'), table_name='homeworks')
    op.drop_table('homeworks')
    op.drop_index(op.f('ix_voice_analyses_user_id'), table_name='voice_analyses')
    op.drop_index(op.f('ix_voice_analyses_status'), table_name='voice_analyses')
    op.drop_table('voice_analyses')
    op.drop_index(op.f('ix_speech_analyses_user_id'), table_name='speech_analyses')
    op.drop_index(op.f('ix_speech_analyses_status'), table_name='speech_analyses')
    op.drop_table('speech_analyses')
    op.drop_index(op.f('ix_push_tokens_user_id'), table_name='push_tokens')
    op.drop_table('push_tokens')
    op.drop_table('push_notifications')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_external_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_observation_attempts_user_id'), table_name='observation_attempts')
    op.drop_table('observation_attempts')
    op.drop_index(op.f('ix_lessons_course_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_enrollments_user_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_certificates_user_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_serial_number'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_course_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index(op.f('ix_audiobook_progress_user_id'), table_name='audiobook_progress')
    op.drop_index(op.f('ix_audiobook_progress_audiobook_id'), table_name='audiobook_progress')
    op.drop_table('audiobook_progress')
    op.drop_index(op.f('ix_audiobook_pages_audiobook_id'), table_name='audiobook_pages')
    op.drop_table('audiobook_pages')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('pronunciation_references')
    op.drop_index(op.f('ix_observation_tests_order_index'), table_name='observation_tests')
    op.drop_index(op.f('ix_observation_tests_is_active'), table_name='observation_tests')
    op.drop_table('observation_tests')
    op.drop_index(op.f('ix_courses_slug'), table_name='courses')
    op.drop_index(op.f('ix_courses_is_published'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_audiobooks_slug'), table_name='audiobooks')
    op.drop_index(op.f('ix_audiobooks_is_published'), table_name='audiobooks')
    op.drop_index(op.f('ix_audiobooks_is_free'), table_name='audiobooks')
    op.drop_table('audiobooks')
    # ### end Alembic commands ###
